name: "OwnTracks Recorder"
version: "0.0.11"
slug: "owntracks_recorder"
description: "Backend for the OwnTracks apps to store and visualize location data."
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
init: false
options:
  otr_host: "core-mosquitto"
  otr_user: "your_mqtt_username"
  otr_pass: "your_mqtt_password"
schema:
  otr_host: str
  otr_user: str
  otr_pass: str
ports:
  8083/tcp: 8083
map:
  - share:rw
