name: "Owntracks Recorder"
description: "A lightweight program for storing and accessing location data published via MQTT by the OwnTracks apps."
version: "0.0.4"
slug: "owntracks_recorder"
arch:
  - aarch64
  - amd64
startup: services
boot: auto

ports:
  8083/tcp: 8083

map:
  - type: addon_config
    read_only: false
    path: /config
  - type: data
    read_only: false
    path: /store

options:
    otr_host: "127.0.0.1"
    otr_port: 8083
    otr_user: "mqtt_user"
    otr_pass: "mqtt_pass"

schema:
  otr_host: str
  otr_port: int
  otr_user: str?
  otr_pass: password?