name: "Owntracks Recorder"
description: "A lightweight program for storing and accessing location data published via MQTT by the OwnTracks apps."
version: "latest"
slug: "owntracks_recorder"
arch:
  - aarch64
  - amd64
image: owntracks/recorder
startup: services
boot: auto

ports:
  8083/tcp: 8083

map:
  - type: addon_config
    read_only: false
    path: /config
  - type: data
    read_only: false
    path: /store

options:
    otr_host: "127.0.0.1"
    otr_port: 8083
    otr_user: "mqtt_user"
    otr_pass: "mqtt_pass"

schema:
  otr_host:
    type: str
    description: "The hostname or IP address of the MQTT broker."
  otr_port:
    type: int
    description: "The port number of the MQTT broker."
  otr_user:
    type: str?
    description: "The username for authenticating with the MQTT broker."
  otr_pass:
    type: str?
    description: "The password for authenticating with the MQTT broker."

environment:
    OTR_HOST: otr_host
    OTR_PORT: otr_port
    OTR_USER: otr_user
    OTR_PASS: otr_pass