ARG BUILD_FROM=alpine:latest
FROM owntracks/recorder:latest

# Map Home Assistant options to container environment variables
ENV OTR_HOST=core-mosquitto
ENV OTR_USER=otr_user
ENV OTR_PASS=otr_pass

EXPOSE 8083
