ARG BUILD_FROM=alpine:latest
FROM owntracks/recorder:latest

# Environment variables mapping configuration options to the container
ENV OTR_HOST=core-mosquitto

# Expose the default UI and API port
EXPOSE 8083
